name: Test Actions

on:
  workflow_dispatch:

jobs:
  install-c2p:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install C2P
        id: install
        uses: ./actions/setup-c2pcli
      - run: echo ${{ steps.install.outputs.c2p-version }}
